### ISSUE TITLE
Create any example of hello world in another language

### ISSUE THREAD

**Issue by berviantoleo** [berviantoleo/hello-world#1]
I hope this repository will provide any example of hello word from many programing language. Also if have a good suggestion about testing set, it will good.

**Comment by esafirm** [comment]
This is cool but i think you have to add readme or some guide to actually run those hello world?

**Comment by Fernando-Erd** [comment]
in Go language
```
package main

import "fmt"

func main() {
    fmt.Printf(Hello World!\n")
}
```

**Comment by josephyi** [comment]
Remember, the PR has to be made Oct 1 for Hacktoberfest credit!

**Comment by esafirm** [comment]
@josephyi this is just a warm-up 😂

**Comment by matheuscr30** [comment]
Can I do this?

**Comment by berviantoleo** [comment]
@matheuscr30 sure. feel free to contribute in this repository.

**Comment by saranagui** [comment]
@berviantoleo hello :) I tried commiting then pushing but it says permission denied. Where should I push? Thanks in advance!

**Comment by berviantoleo** [comment]
@saranagui you should fork this repository, clone your forked repository, commit on that repository, push, then you open pull request to this repository.
